import { ResourcePaper } from "@/lib/types";

export const resourcesData: ResourcePaper[] = [
  {
    id: "pyq-jee-adv-2025",
    title: "JEE Advanced 2025 Official Question Paper 1 & 2",
    exam: "JEE Advanced",
    year: 2025,
    subjectOrSession: "Paper 1 & Paper 2 (PCM Combined)",
    type: "Question Paper",
    fileSize: "2.4 MB",
    format: "PDF",
    downloadFileName: "JEE_Advanced_2025_Official_Paper_Glorious_Academy.pdf",
    sourceAttribution: "Official Examination Archive (IIT Madras/Organizing Agency)",
    verificationStatus: "approved",
  },
  {
    id: "pyq-jee-adv-2023",
    title: "JEE Advanced 2023 Question Paper with Official Key",
    exam: "JEE Advanced",
    year: 2023,
    subjectOrSession: "Paper 1 & Paper 2 (Complete)",
    type: "Answer Key & Solution",
    fileSize: "3.1 MB",
    format: "PDF",
    downloadFileName: "JEE_Advanced_2023_Paper_and_Solutions.pdf",
    sourceAttribution: "Official Examination Archive",
    verificationStatus: "approved",
  },
  {
    id: "pyq-jee-main-2025-jan",
    title: "JEE Main 2025 (Session 1 - January) All Shifts Paper Compilation",
    exam: "JEE Main",
    year: 2025,
    subjectOrSession: "Session 1 (January Shifts PCM)",
    type: "Question Paper",
    fileSize: "4.2 MB",
    format: "PDF",
    downloadFileName: "JEE_Main_2025_Session1_Question_Papers.pdf",
    sourceAttribution: "National Testing Agency (NTA) Archive",
    verificationStatus: "approved",
  },
  {
    id: "pyq-jee-main-2024",
    title: "JEE Main 2024 Chapter-Wise Questions with Answer Key",
    exam: "JEE Main",
    year: 2024,
    subjectOrSession: "Physics, Chemistry & Mathematics",
    type: "Answer Key & Solution",
    fileSize: "5.8 MB",
    format: "PDF",
    downloadFileName: "JEE_Main_2024_Chapterwise_Questions_Solutions.pdf",
    sourceAttribution: "NTA Examination Archive & Glorious Academy Academic Cell",
    verificationStatus: "approved",
  },
  {
    id: "pyq-jee-main-2023",
    title: "JEE Main 2023 Question Papers (Both Sessions)",
    exam: "JEE Main",
    year: 2023,
    subjectOrSession: "January & April Session Papers",
    type: "Question Paper",
    fileSize: "4.0 MB",
    format: "PDF",
    downloadFileName: "JEE_Main_2023_Question_Papers.pdf",
    sourceAttribution: "National Testing Agency (NTA)",
    verificationStatus: "approved",
  },
  {
    id: "pyq-neet-2025",
    title: "NEET (UG) 2025 Question Paper with Official Code Solutions",
    exam: "NEET",
    year: 2025,
    subjectOrSession: "Physics, Chemistry, Botany & Zoology",
    type: "Question Paper",
    fileSize: "3.4 MB",
    format: "PDF",
    downloadFileName: "NEET_UG_2025_Official_Question_Paper.pdf",
    sourceAttribution: "National Testing Agency (NTA)",
    verificationStatus: "approved",
  },
  {
    id: "pyq-neet-2024",
    title: "NEET (UG) 2024 Question Paper and Detailed Answer Key",
    exam: "NEET",
    year: 2024,
    subjectOrSession: "Complete 720 Marks Paper",
    type: "Answer Key & Solution",
    fileSize: "3.8 MB",
    format: "PDF",
    downloadFileName: "NEET_UG_2024_Question_Paper_With_Keys.pdf",
    sourceAttribution: "National Testing Agency (NTA)",
    verificationStatus: "approved",
  },
  {
    id: "pyq-neet-2023",
    title: "NEET (UG) 2023 Question Paper (Code E, F, G, H)",
    exam: "NEET",
    year: 2023,
    subjectOrSession: "PCB Full Syllabus",
    type: "Question Paper",
    fileSize: "2.9 MB",
    format: "PDF",
    downloadFileName: "NEET_UG_2023_Official_Paper.pdf",
    sourceAttribution: "National Testing Agency (NTA)",
    verificationStatus: "approved",
  },
  {
    id: "pyq-cet-2024",
    title: "MHT-CET 2024 PCM Shift-wise Memory-Based Question Archive",
    exam: "MHT-CET",
    year: 2024,
    subjectOrSession: "PCM Morning & Afternoon Shifts",
    type: "Question Paper",
    fileSize: "2.1 MB",
    format: "PDF",
    downloadFileName: "MHT_CET_2024_PCM_Paper_Archive.pdf",
    sourceAttribution: "Maharashtra State CET Cell / Academic Compilation",
    verificationStatus: "approved",
  },
  {
    id: "pyq-cbse-10-2024",
    title: "CBSE Class 10 Board Science & Mathematics 2024 Question Papers",
    exam: "CBSE Class 10",
    year: 2024,
    subjectOrSession: "Standard Math & Science (Set 1, 2, 3)",
    type: "Question Paper",
    fileSize: "1.8 MB",
    format: "PDF",
    downloadFileName: "CBSE_Class10_2024_Board_Papers.pdf",
    sourceAttribution: "Central Board of Secondary Education (CBSE)",
    verificationStatus: "approved",
  },
  {
    id: "pyq-cbse-12-2024",
    title: "CBSE Class 12 Board Physics & Chemistry 2024 with Marking Scheme",
    exam: "CBSE Class 12",
    year: 2024,
    subjectOrSession: "Theory & Problem Solving Scheme",
    type: "Answer Key & Solution",
    fileSize: "2.5 MB",
    format: "PDF",
    downloadFileName: "CBSE_Class12_2024_Physics_Chemistry_MarkingScheme.pdf",
    sourceAttribution: "Central Board of Secondary Education (CBSE)",
    verificationStatus: "approved",
  },
];
